### ISSUE TITLE
How to use start Index and End Index

### ISSUE THREAD

**Issue by niveshsaharan** [iotaledger/iota.lib.js#101]
I know that we can pass int values in start Index and End index. But how would we know that what should be the End index? Let's say I am making a wallet, How can i display user their balance if I don't know the exact End index? And if I pass anything as a guess, won't it make the whole thing slow OR ignore many addresses with non-zero balance?

Please help me understand this, so that I can build something beautiful.

**Comment by chrisdukakis** [comment]
End index should probably be a configurable parameter in your application. 
Please join the [IOTA slack](http://slack.iota.org/), you can ask questions like this in #developers channel.

**Comment by janfiedler** [comment]
In my case start and end index dosent work in function getInputs. Every time takes all and take it more and more time to finish. When new transaction is made.
