### ISSUE TITLE
[Request] Support different coin types in address generation

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota.lib.js#1024]
## Description

Currently the coin type is hardcoded to IOTA https://github.com/iotaledger/iota.js/blob/5f5d149698c2d1f730274d74606e7decaa1574ac/packages/iota/src/highLevel/addresses.ts#L6, but it would be good to have an option to provide other coin types in generateBip44Address()

## Motivation

Make it possible to easily also generate addresses with other coin types, for example shimmer 4219

## Requirements

1. Have a way to specify the coin type for address generation

## Are you planning to do it yourself in a pull request?

No.

**Comment by msarcev** [comment]
Review the PR for this https://github.com/iotaledger/iota.js/pull/1026.
