### ISSUE TITLE
C library

### ISSUE THREAD

**Issue by mankash** [iotaledger/iota.lib.js#108]
If you'd really like to see this being used in IoT, like your mission statement claims, please provide a C library without external dependencies ( save the standard library).

Even if just a thin client, this will ACTUALLY work in the IoT setting, instead of expecting people to port a js interpreter to their IoT device, which, mind you, is starved for CPU & RAM.

**Comment by Citrullin** [comment]
I think it would be better to create a C library instead of a Go Library. More IoT-Devices support C than Go. Or it is way simpler to use C than Go. You can still wrap the C Library in Go.  See => https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command

**Comment by frank-dspeed** [comment]
the couchbase npm and serialport npm are good examples how to use bindings to nativ C libs so we could reuse that even as foundation for this lib.js on server-side

**Comment by anyong** [comment]
C library is on the roadmap, and this is not an issue with iota.lib.js. I'll close this issue, but we definitely appreciate your thoughts!
