### ISSUE TITLE
[Task] Merge outstanding PRs (dependabot + tutorials)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota.lib.js#1086]
## Description

- There are lot of dependabot PRs open. Merge one by one an test (close the ones that break the build, if any)
- Check and merge the tutorial PRs

## Motivation

Cleanup the open PRs tab

**Comment by rajivshah3** [comment]
If Dependabot gets too noisy, the config is located [here](https://github.com/iotaledger/iota.js/blob/dev/.github/dependabot.yml). The docs for the `dependabot.yml` config are [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) in case you want to change the schedule or other settings
