### ISSUE TITLE
Add Eslint linting utility

### ISSUE THREAD

**Issue by reyraa** [iotaledger/iota.lib.js#116]
## Why bother linting?
I think this project needs a linting library like Eslint for these reasons:
 - To ensure follow the same code styling all over the code, specially if we expect the community to actively contribute.
 - To make the on boarding of the open source developers easy, since we share the same code style.
 - Prevents many roots of bugs like mutability of reference values.
 - IOTA deserves it!

## Why Eslint?
There are many articles of this, read [this](https://hackernoon.com/how-linting-and-eslint-improve-code-quality-fa83d2469efe) for example.

## Steps we need to take
With the current code style, such a migration requires 4 steps:
 - First we need to have the configuration in place on which we all consent. #117 
 - Then we need to perform automatic fixings using one the existing libraries. this results in a big but easy-to-review PR, this the glorious time for our tests helping us make sure nothing is broken.
 - Then we need to fix Eslint error that automatic fixers can not change/fix. 
 - Finally, Add eslint to CI so all PRs require eslint to pass.

**Comment by jkoudys** [comment]
Why is this still open? I think there are lots of devs (myself included) who would love to be active contributors, but don't want to start adding code to the hodge-podge of inconsistent standards and obsolete practices that are in the current codebase. I'm happy to do all the work and update this myself, but I'm not sure I want to take the time to do that when there's a 4-month-old PR gathering dust already.

**Comment by anyong** [comment]
The `next` branch includes [tslint](https://github.com/iotaledger/iota.lib.js/blob/next/tslint.json) and [prettier](https://github.com/iotaledger/iota.lib.js/blob/next/.prettierrc) support for code formatting and linting.

@jkoudys you're absolutely right, and we are focused on getting those PRs resolved and old practices updated, as I hope you can tell :)
