### ISSUE TITLE
defaults documentation

### ISSUE THREAD

**Issue by ysle** [iotaledger/iota.lib.js#119]
can we have the default values documented for the getNewAddress options please ?
I mean here : https://github.com/iotaledger/iota.lib.js#getnewaddress

**Comment by chrisdukakis** [comment]
Thank you for this suggestion! All params of `getNewAddress`, and rest of  API methods, are now documented [here](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.getNewAddress). Please note that this documentation describes __`v >= 1.0.0-alpha.1`__.
