### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by NicoleZA** [iotaledger/iota.lib.js#122]
is there a reference.d.ts file for typescript?

**Comment by michaelprzybyla** [comment]
@NicoleZA just npm install @types/iota.lib.js

**Comment by robertohuertasm** [comment]
Just out of curiosity, is there any plan on migrating this project to `Typescript`?

**Comment by mpaland** [comment]
I've started a complete rewrite last year to review and clean things up, working on it...
https://github.com/mpaland/iota.lib.ts

Converter, Bundle, Kerl and Curl are working so far...
API and signing is in progress.

**Comment by anyong** [comment]
iota.lib.js v1 (currently available in [alpha](https://github.com/iotaledger/iota.lib.js/tree/next)) is fully re-written in TypeScript.
