### ISSUE TITLE
getBalances not part of the api documentation

### ISSUE THREAD

**Issue by henningvs** [iotaledger/iota.lib.js#123]
Is there a reason why nowhere the following api call has been documented?

`iota.api.getBalances(addresses, threshold, callback)`

**Comment by mrbianchi** [comment]
because is the api of IRI, all commands are included

**Comment by chrisdukakis** [comment]
Thank you for reporting this! `getBalances()` is now [documented here](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.getBalances). Please note that this documentation accurately describes __`v >= 1.0.0-alpha.1`__.
