### ISSUE TITLE
Sandbox http issue

### ISSUE THREAD

**Issue by trickstival** [iotaledger/iota.lib.js#128]
Hey guys I’m not being able to get a http response from http://sandbox.iotatoken.com/api/v1/

When I try to put this link as a provider it turns me an error:

 — Code  — 
```
var iota = new IOTA({
‘provider’ : ‘http://sandbox.iotatoken.com/api/v1/',
‘sandbox’ : true,
‘token’ : ‘here is my token’
})
iota.api.getTips(function(error, success) {
if(error){
console.error(‘getting an error’, error)
}
if(success){
console.info(‘you did it well’, success)
}
})
```
 — The Console Error — 
Error: Invalid Response: 
 at Object.invalidResponse (requestErrors.js?0f3b:5)
 at makeRequest.prepareResult (makeRequest.js?c17f:160)
 at XMLHttpRequest.request.onreadystatechange (makeRequest.js?c17f:62)

When I try curl http://sandbox.iotatoken.com/api/ or http://sandbox.iotatoken.com/api/v1/ it does not work either:
Host “http://sandbox.iotatoken.com/api/[v1/]" could not be found

Do you have any ideia of what’s going on?

**Comment by alessandrocuzzocrea** [comment]
Same here:

> Something went wrong:  Error: Invalid Response: Error: getaddrinfo ENOTFOUND sandbox.iotatoken.com sandbox.iotatoken.com:443

**Comment by tchoule84** [comment]
Same for me :/

**Comment by Plarixtu** [comment]
https://dev.iota.org/ also does not work anymore - last week I was still able to acceess it. 

Can anybody tell me how I can get a Sandbox auth token? I tried to reach out to the devs by Email last week but didn't receive a response yet.

I'm trying to wrap my head around how to use the API, but honestly it's not made easy like this :/

**Comment by Plarixtu** [comment]
http://slack.iota.org/ is also down and there is no explenation on how I can register an account at the https://forum.iota.org/ (you can only login but not register an account).

It seems quite difficult to get involved. Why?

**Comment by chrisdukakis** [comment]
Sandbox has been upgraded. Please check https://powbox.testnet.iota.org/ and [`curl-remote`](https://www.npmjs.com/package/@iota/curl-remote) package.
