### ISSUE TITLE
[getNewAddress] index incrementation doesn't change anything

### ISSUE THREAD

**Issue by tiresias54** [iotaledger/iota.lib.js#13]
I generate a new address with the javascript command: 

`var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var performance = require("performance-now");

var IOTA = require("iota.lib.js");

var seed = "RANDOMSEED"

var iota = new IOTA({
        'host': 'http://localhost',
            'port': 33333
});

iota.api.getNewAddress(seed,[0,true,1,true],function(e,s) {
        console.log("ERROR: "+e);
            console.log("ADDRESS: "+s);
});
`
Then I try to increment the argument 'index' of getNewAddress in order to generate a new address: 

`var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var performance = require("performance-now");

var IOTA = require("iota.lib.js");

var seed = "RANDOMSEED"

var iota = new IOTA({
        'host': 'http://localhost',
            'port': 33333
});

iota.api.getNewAddress(seed,[1,true,1,true],function(e,s) {
        console.log("ERROR: "+e);
            console.log("ADDRESS: "+s);
});
`

I also try to generate a list of address with the command 

`var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

var performance = require("performance-now");

var IOTA = require("iota.lib.js");

var seed = "RANDOMSEED"

var iota = new IOTA({
        'host': 'http://localhost',
            'port': 33333
});

iota.api.getNewAddress(seed,[1,true,5,true],function(e,s) {
        console.log("ERROR: "+e);
            console.log("ADDRESS: "+s);
});`

but no matter what argument i set, i always have the return 

`ERROR: null

ADDRESS: X9MDSKGMQKG9SWDNHCZL9QLINUWSVYZUXMGOCCDXRTQCRWSUZNIELZWOQBSJNFO9SKYGYASF9SEBGCIIJ`

**Comment by domschiener** [comment]
Second input is an *object*. 

```
iotajs.api.getNewAddress(seed, {'index': 1, 'checksum': true, 'total': 5, 'returnAll': true}, ...)
```
