### ISSUE TITLE
traverseBundle fails with empty transaction

### ISSUE THREAD

**Issue by mark-bradshaw** [iotaledger/iota.lib.js#14]
In `lib/api/api.js` traverseBundle around line 1271 you get a failure if `getTrytes` returns an empty `trytesList.trytes` array. The whole functions throws an error and kills down a few lines when it starts looking for things like `txObject.bundle`.  Does this mean that a transaction is malformed or there's missing data?  I'm not sure what the appropriate response should be from traverseBundle when this occurs?

I suspect that's what line 1277, `if (trytes === null) return callback(new Error("Bundle transactions not visible"))`, was trying to catch.  If so, just changing that to `if (!trytes)` should do the trick.  That'll catch both null and undefined.  When I change that out the bug I'm hitting seems to disappear.

**Comment by domschiener** [comment]
Fixed. Will push soon (with some other additions).
