### ISSUE TITLE
How can i generate seed via iota.lib.js?

### ISSUE THREAD

**Issue by avihaiandroid** [iotaledger/iota.lib.js#145]
I know this is a stupid question but i really can't find how

edit:
It is secure this way:?
let seed;
let randomstring = require("randomstring")
seed = randomstring.generate({
			charset: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ9',
			length: 81
		});

**Comment by gagathos** [comment]
https://www.npmjs.com/package/iota-generate-seed has worked for me. It uses similar code to you

```
'use-strict'

const randomstring = require('randomstring');

const length = 81;
const charset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ9';

module.exports = () => {
  return randomstring.generate({
    length: length,
    charset: charset
  });
};
```

**Comment by avihaiandroid** [comment]
Now i use this lib:
https://github.com/knarz/seedgen

With this lib you can generate the seed in the client easily and its more random then randomstring

**Comment by tawago** [comment]
@avihaiandroid 
It seems you resolved it by yourself. Could you close this issue please?
