### ISSUE TITLE
getNewAddress calls findTransactions with checksummed addresses

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota.lib.js#149]
Hi,

As I understand it, findTransactions only accepts addresses without their checksum.
Calling it with a checksummed address would lead to the error "Invalid addresses input".

https://github.com/iotaledger/iota.lib.js/blob/141df389a9ead2e83fbc2cf913cbff6818347618/lib/api/api.js#L861

In this case (Case 2: no total provided), providing checksum=true to api.prototype.getNewAddress calls findTransactions with checksummed addresses, resulting in the previously cited error.

Correct way to do it would be to call self._newAddress with checksum=false and checksum the address after calling findTransactions.

Am I missing something ?

Thanks in advance,

**Comment by chrisdukakis** [comment]
hey @thibault-martinez,
I presume you observed this on an outdated version. There was a patch that truncates addresses on all relevant API calls, so you don't have to worry about passing the checksum or not.
For more info see #109

**Comment by thibault-martinez** [comment]
@chrisdukakis,

You are totally right, I didn't see that patch.

Thank you for the clarification :)
