### ISSUE TITLE
Reject with meaningful error if getBundle is called on non-tail hashes

### ISSUE THREAD

**Issue by videfrancisco** [iotaledger/iota.lib.js#151]
Hi friends, im trying to use sendtransfer, but return invalid bundle when i try replaybundle or use reattach.online. Im using node, the code bellow i get from https://iota.readme.io/v1.2.0/docs/withdrawal-processing-monitoring

I try many times, the transaction show in thetangle.org but not working

The transactions show in input and destination address

https://thetangle.org/address/IEYWBCFFGJABY9MEESPAT9GIROVZUZVHNKV9UKTCBWW9ZZQTQIDUKOOJSDM9GNDFMHF9AVFZHFKXNYMRW

https://thetangle.org/address/UJQFJCGMGTRJYVO9FMIXQQBIPTJLMAOLVVCLGHKVPCJSGODVPNJGGSDDIMZJSQTEGJWUNYECJVEZUFHWA

Can one help?

const tryteseed = iota.utils.toTrytes(seed);
const transfers = [
   {
       address: 'IEYWBCFFGJABY9MEESPAT9GIROVZUZVHNKV9UKTCBWW9ZZQTQIDUKOOJSDM9GNDFMHF9AVFZHFKXNYMRW',
       value: 1000000,
       message: '',
       tag: ''
   }
]

const inputs = [
   {
       address: 'UJQFJCGMGTRJYVO9FMIXQQBIPTJLMAOLVVCLGHKVPCJSGODVPNJGGSDDIMZJSQTEGJWUNYECJVEZUFHWA',
       keyIndex: 1,
       security: 1,
       balance: 1000000
   }
]

const options = {
   inputs: inputs
}

const depth = 4
const minWeightMagnitude = 14

const withdrawalHashes = []

iota.api.sendTransfer(tryteseed, depth, minWeightMagnitude, transfers, options, (err, transactions) => {
   if (err) {
       console.log(err)
   }    console.log(transactions); 
});

**Comment by tawago** [comment]
you may want to ask in https://iota.stackexchange.com/

**Comment by chrisdukakis** [comment]
@videfrancisco Looking at the transactions, they seem to be valid. `replayBundle(tail)` works with tail transaction hash, which the hash of transaction with `currentIndex=0`. I assume that non-tail hash caused the `invalid bundle` error.

I leave this issue open to add proper validation and error message for non-tails in [getBundle()](https://github.com/iotaledger/iota.lib.js/blob/next/lib/api/extended/createGetBundle.ts).

**Comment by chrisdukakis** [comment]
Tail transaction check was implemented for `v.1.0.0.alpha`(https://github.com/iotaledger/iota.lib.js/blob/c810a98636fe421f6d032ef705564a61a451e099/packages/core/src/createTraverseBundle.ts#L59). It seems that all other cases of invalidation are because of syntactically invalid bundles. This is also the case for prior releases prior to `v1.0.0-alpha`.
