### ISSUE TITLE
webpack warning "Critical dependency"

### ISSUE THREAD

**Issue by hynese** [iotaledger/iota.lib.js#158]
After a simple `import {IOTA} from 'iota.lib.js'` in my React.js component, I'm now getting the following when running `./node_modules/.bin/webpack-dev-server --hot`

```
WARNING in ./node_modules/iota.lib.js/lib/utils/makeRequest.js
10:16-31 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/iota.lib.js/lib/utils/makeRequest.js
 @ ./node_modules/iota.lib.js/lib/iota.js
 @ ./src/components/Graph.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index
```

```
var async = require("async");
var errors = require("../errors/requestErrors");

function xmlHttpRequest() {
  if (typeof XMLHttpRequest !== 'undefined') {
    return new XMLHttpRequest();
  }

  var module = 'xmlhttprequest';
  var request = require(module).XMLHttpRequest;    //this line seems to cause warnings...
  return new request();
}

function makeRequest(provider, token) {

    this.provider = provider || "http://localhost:14265";
    this.token = token;
}
```

**Comment by chrisdukakis** [comment]
@hynese could you try to replace `require(module)` with `require('xmlhttprequest')` ?
Looking at https://webpack.js.org/guides/code-splitting/#dynamic-imports , I presume that the _root path_ shouldn't be an expression.
Please let me know if this solves the issue, to include it in next release.

**Comment by rajivshah3** [comment]
After looking at https://github.com/webpack/webpack/issues/196, I wonder if #164 might help here as well?

**Comment by deepanigi** [comment]
I am facing the same problem i am using iota lib in angular app

> Failed to load https://potato.iotasalad.org:14265/: Response for preflight is invalid (redirect)
home.component.ts:55 Error: Invalid Response: 
    at Object.invalidResponse (requestErrors.js:5)
    at makeRequest.webpackJsonp.../../../../iota.lib.js/lib/utils/makeRequest.js.makeRequest.prepareResult (makeRequest.js:285)
    at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (makeRequest.js:71)
    at XMLHttpRequest.wrapFn (zone.js:1166)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1517)
client?ffdb:120 [WDS] Warnings while compiling.
warnings @ client?ffdb:120
sock.onmessage @ socket.js:37
webpackJsonp.../../../../sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:274
webpackJsonp.../../../../sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:272
webpackJsonp.../../../../sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
wrapFn @ zone.js:1166
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:188
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
client?ffdb:126 ./node_modules/iota.lib.js/lib/utils/makeRequest.js
10:16-46 Critical dependency: the request of a dependency is an expression

**Comment by laubsauger** [comment]
@chrisdukakis Yep, you only have to replace that dynamic import with `require('xmlhttprequest')`

**Comment by minyc510** [comment]
Hello, I am having the same issue however, I don't ever use `require(module)`.

**The following line single-handedly causes the error:**
`import IOTA from '../node_modules/iota.lib.js/lib/iota.js'`

The error:
```
./node_modules/iota.lib.js/lib/utils/makeRequest.js
10:16-46 Critical dependency: the request of a dependency is an expression
```
I am working in a fresh [create-react-app](https://github.com/facebook/create-react-app) project.

**Comment by chrisdukakis** [comment]
As of `v1.0.0-alpha.1` this silly dynamic import is well gone. Also, new packages [`iota/core`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core) & [`iota/http-client`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/http-client) use `fetch` to make requests.

**Comment by minyc510** [comment]
Can someone let me know how to update to v1.0.0-alpha.1?
