### ISSUE TITLE
getNewAddress will still generate an address if given a seed shorter than 81 characters

### ISSUE THREAD

**Issue by minyc510** [iotaledger/iota.lib.js#160]
**EDIT: It appears that this is actually the intended result of the getNewAddress function when given a short seed.** 

I noticed the getNewAddress function will not return an error, but still generate a new address given a seed shorter than 81 characters. The following is an example:

```javascript
var seed = 'SHORTSEED';`

iota.api.getNewAddress(seed, options, function(error, addresses) {
	if (error) { console.log('Error!') }
	else { console.log(addresses[0]); }
});
```

When I run this short java script code the console will print

`REFFLFXNGESFMFBCIJJBWRSXMBIZKPQSFWHMACNCYWAIDCRTRYOXQFXVTQP9RZEDXEVHQMJUIHXNI9MYXBGNK9CGAC`

**Comment by frank-dspeed** [comment]
@minyc510 hmmm is that a bug do you think this should error=? if so i would say i can do a PR for that simply ping me

**Comment by frank-dspeed** [comment]
@minyc510 i investigated as the SEED gets hashed this is the intended behavior of this function your short SEED results in a 81 hash all is fine.

**Comment by minyc510** [comment]
@frank-dspeed I appreciate the reply! Could you clarify? 

So the getNewAddress function is designed so that if a user has a short seed, the function will use that short seed to hash another seed that is 81 characters long and use that to generate the new address?
