### ISSUE TITLE
Message lost when making multisign transfer

### ISSUE THREAD

**Issue by waglik** [iotaledger/iota.lib.js#163]
I believe that message is lost in case of multisign transfer. I am following github example but instead of empty string I am sending a Trytes :  

```
var messageToSend = {
    'name': 'Matt',
    'message': 'My first multisig message sent with IOTA.'
}

var messageStringified = JSON.stringify(messageToSend);

var messageTrytes = iota.utils.toTrytes(messageStringified);

var multisigTransfer = [
    {
        address: send2address,
        value: 1,
        message: messageTrytes,
        tag: '9'.repeat(27)
    }
];
```

Now in order to send data to the network I do : 

```
iota.api.prepareTransfers(seedA,finalBundle, (e,trytes) => {

                    if (e) throw e;

                    iota.api.sendTrytes(trytes, 4, 14, function (e, bundle) {
                        if (e) throw e;
                        console.log("Successfully sent your transfer: ", bundle);
                    });
});
```

the result is : 

[transaction](https://thetangle.org/transaction/RPYOVHIRVQODWLNKXVLXD9GXNOZSTYCXQGEGVAT9N9ULKIMLNFRWYVSZQNJTQ99TTIFPKIFQQILT99999)

however if I do an extra step : 

```
for (var i = 0; i < finalBundle.length; i++) {
                    finalBundle[i].message = finalBundle[i].signatureMessageFragment ? 
                    finalBundle[i].signatureMessageFragment : '';
}

iota.api.prepareTransfers ....

```

the result is : 

[transaction](https://thetangle.org/transaction/CQQYBGYMITBFZOGVDYVYCJKAOL9WFXDLWBSNQ99UHNDCKMJBTNKBQML9FPNAPA9JMXUIOUZHXT9HZ9999) 

if I understand it's because prepareTransaction looks for message property and just ignores signatureMessageFragment. 

Unless I am trying to send transaction wrongly but can not find any information about that and was using Python examples as reference.

**Comment by chrisdukakis** [comment]
This is because of incorrect usage of `prepareTransfers()`. In fact you don't need it, because multisig methods prepare the transfers for you. To send the multisig transfer you need to use `sendTrytes()` which accepts an array of `trytes`. Convert each transaction in`finalBundles` to  `trytes` with the utility method and reverse the array of trytes:
```js
finalBundle.map(tx => iota.utils.transactionTrytes(tx)).reverse()
```

To attach the trytes on tangle do:
```js
iota.api.sendTrytes(trytes, depth, minWeightMagnitude, callback)
```

Finally look for the msg at transaction with `currentIndex: 0`

I'll add an explanation in docs and example, until then let's keep this issue open.

**Comment by waglik** [comment]
@chrisdukakis Thanks it helped. 

However on the side note I can not read back message so I guess I am doing still something wrong. For example this [transaction](https://thetangle.org/transaction/QJLXHVJDJAMYDSBLBEFODXAHVNYBBDD9FMKTJLEKBMWEIDGYZC9C9AXMPVZCMSP9HCCRBFYJXWT999999)

```
var multiSignTransactionHash = 'QJLXHVJDJAMYDSBLBEFODXAHVNYBBDD9FMKTJLEKBMWEIDGYZC9C9AXMPVZCMSP9HCCRBFYJXWT999999';

iota.api.getTransactionsObjects([multiSignTransactionHash], (err,objects) => {

    if (err) console.log(err);
    var x = objects[0].signatureMessageFragment;
    console.log(iota.valid.isTrytes(x));
    console.log(iota.utils.fromTrytes(x));

});

```
will print 

true
null

it's because x is odd. If I add extra character to x 

`console.log(iota.utils.fromTrytes(x+'9'));`

It will print message plus some garbage. 

Should I sanitize Trytes somehow? Should I remove trailing 9s manually?

**Comment by waglik** [comment]
@chrisdukakis Thanks. It works great! Can I bother you with one last question? What does value represents and why it needs to be >0 ? I tried to send 0 valued mutlisign transfer but it would fail.

**Comment by chrisdukakis** [comment]
It represents the value of iotas, transferred from multisig address to output addresses, defined in transfers array.

**Comment by waglik** [comment]
@chrisdukakis but why is zero allowed?
