### ISSUE TITLE
Why callbacks for everything

### ISSUE THREAD

**Issue by mmclau14** [iotaledger/iota.lib.js#168]
hi there, just a quick question, why were callbacks used for everything instead of promises? i don't see an explicit node version in the package.json. is this a feature that you guys would like to include?

**Comment by rajivshah3** [comment]
You can promisify the lib if you use Bluebird's `Promise.promisifyAll`: http://bluebirdjs.com/docs/api/promise.promisifyall.html

**Comment by anyong** [comment]
Promises will be supported in v1, currently available on the [`next` branch](https://github.com/iotaledger/iota.lib.js/tree/next).
