### ISSUE TITLE
Gulp...

### ISSUE THREAD

**Issue by Qws** [iotaledger/iota.lib.js#175]
How to get pass Gulp easily? 

Because every time I use the "gulp" command in the "dist" folder, it keeps asking me for to manually install NPM modules like Browserfy, gulp-lint, gulp-rename, venyl-buffer...

Can anyone help me? I just want to try the IOTA library with Node.js. Do I really have to install all the dependencies? Even Brower and Mocha?

**Comment by rajivshah3** [comment]
If you just want to use this library with NodeJS, you just need to run `npm install iota.lib.js` or `yarn add iota.lib.js`. The steps that talk about gulp seem to be if you want to use the library in a browser (e.g. make a website that integrates the library). If you need to use it in a browser, I personally prefer browserify (http://browserify.org/). I used it in https://github.com/rajivshah3/iota-pow-er, all you need to do is run `browserify myfile.js > myfile-bundle.js`.

**Comment by Qws** [comment]
@rajivshah3 I see... thanks! It works now.

Was kinda confused with Gulp and Bowser.

**Comment by rajivshah3** [comment]
Great! You can close this issue if everything’s resolved.
