### ISSUE TITLE
Bug in api.prototype.getInputs

### ISSUE THREAD

**Issue by joseph14** [iotaledger/iota.lib.js#180]
The error check is to see if start is greater then end. However if start is equal to end the function also will fail, because the loop starts at "start" and ends one before "end". (looks like a 1 off error to me)

```
    // If start value bigger than end, return error
    // or if difference between end and start is bigger than 500 keys
    if (options.end && (start > end || end > (start + 500))) {
        return callback(new Error("Invalid inputs provided"))
    }

```

```
        for (var i = start; i < end; i++) {

            var address = self._newAddress(seed, i, security, false);
            allAddresses.push(address);
        }


```

**Comment by chrisdukakis** [comment]
This is [fixed in `v.1.0.0`](https://github.com/iotaledger/iota.lib.js/commit/1b545648c8dca019df7f92e016752928172c6e2e#diff-890d0db1de0af22622b09ddaabf849bdR46)
I keep this issue open to add additional integration tests on calling `getInputs()` with `end` & `threshold` options.

**Comment by chrisdukakis** [comment]
Tests were add: https://github.com/iotaledger/iota.lib.js/blob/9cb3b74e1df332a436e613e83d71573c6b4c685d/packages/core/test/integration/getInputs.test.ts#L122
Also `start` & `end` are validated with this new guard method:
https://github.com/iotaledger/iota.lib.js/blob/9cb3b74e1df332a436e613e83d71573c6b4c685d/packages/validators/src/validators.ts#L343
