### ISSUE TITLE
How can i know if transaction reatch confirm?

### ISSUE THREAD

**Issue by avihai-developer** [iotaledger/iota.lib.js#181]
How can i know if transaction reatch confirm?

**Comment by dsir-minute** [comment]
have a look at my code here
https://github.com/dsir-minute/iotaLeaderBoard2

**Comment by chrisdukakis** [comment]
@avihai-developer You need to monitor all transactions (original tx & reattachments). You can periodically refresh the list by querying by address of the tail transaction and grouping by bundle hash.
I think it's helpful to examine the problem in the context of reattachment & promotion. New docs have a section about it:
https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#example-with-promotion-and-reattachments
