### ISSUE TITLE
I can't read chinese

### ISSUE THREAD

**Issue by agentpx** [iotaledger/iota.lib.js#191]
Please filter the https://forum.iota.org/ according to language you prefer.

**Comment by rajivshah3** [comment]
Hi, http://forum.iota.org is no longer being used. The new forum is at https://forum.helloiota.com

**Comment by laubsauger** [comment]
@agentpx Besides, this has absolutely nothing to do with the code of this library. Please choose appropriate communication channels next time...

**Comment by anyong** [comment]
Closing this issue as not relevant to iota.lib.js.
