### ISSUE TITLE
Feature request - add support for local POW

### ISSUE THREAD

**Issue by avihai-developer** [iotaledger/iota.lib.js#196]
Hi can you please add support for local POW?
Now developers can't use this lib without node that enable POW

**Comment by rajivshah3** [comment]
Check out https://github.com/iotaledger/curl.lib.js, near the bottom there's an `overrideAttachToTangle` function. I believe this is what the wallet uses to force local PoW

**Comment by anyong** [comment]
The `next` branch provides its own [`overrideAttachToTangle`](https://github.com/iotaledger/iota.lib.js/blob/next/lib/api/index.ts#L127-L129) which can be used for local or remote PoW (like via the PoWBox). Documentation is in the works...

**Comment by avihai-developer** [comment]
The POW use CPU / GPU via WebGL2?

**Comment by chrisdukakis** [comment]
Local PoW can be integrated with [`overrideAttachToTangle(newAttachToTangleMethod)`](https://github.com/iotaledger/iota.lib.js/blob/next/api_reference.md#API.overrideAttachToTangle) or [`settings.attachToTangle` in `composeAPI(settings)`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.composeApi). Documentation describes versions >= `v1.0.0-alpha-1`.
