### ISSUE TITLE
TypeError: searchValues.addresses.map is not a function

### ISSUE THREAD

**Issue by ByteFan** [iotaledger/iota.lib.js#201]
let Mykey='addresses';
let Myvalue='RVORZ9SIIP9RCYMREUIXXVPQIPHVCNPQ9HZWYKFWYWZRE9JQKG9REPKIASHUUECPSQO9JT9XNMVKWYGVAZETAIRPTM';
var request= {};
request[Mykey]=Myvalue;
iota.api.findTransactions(request, function(error, success) {
    if (error) {
        console.log(error);
    } else {
        console.log(success);
    }
});

TypeError: searchValues.addresses.map is not a function
    at [stripped for security]/node_modules/iota.lib.js/lib/api/api.js:120:59
    at Array.forEach (<anonymous>)
    at api.findTransactions ([stripped for security]/node_modules/iota.lib.js/lib/api/api.js:110:16)

**Comment by chrisdukakis** [comment]
`Myvalue`  should be array in this case:
```Js
let Myvalue = ['RVORZ9SIIP9RCYMREUIXXVPQIPHVCNPQ9HZWYKFWYWZRE9JQKG9REPKIASHUUECPSQO9JT9XNMVKWYGVAZETAIRPTM']
```
This will be addressed soon with release of TS update, which has guards that verify user inputs or throw comprehensive errors.
For instance, and relevant to this case: https://github.com/iotaledger/iota.lib.js/blob/next/lib/api/core/createFindTransactions.ts#L38

**Comment by ByteFan** [comment]
Oups... my bad. Thank you very much.
