### ISSUE TITLE
getNewAddress should reject with error when called with total=0

### ISSUE THREAD

**Issue by mrbianchi** [iotaledger/iota.lib.js#208]
total=0 shouldn't be valid parameter or if it is valid should return empty array or string as address

and actually it bugges when you use one seed like 999..999 or similar (AA9...999) , returns different address with 0 as total than 1

just try:
`var seed = "999999999999999999999999999999999999999999999999999999999999999999999999999999999";
iota.api.getNewAddress(seed,{index:0,total:0,security:2},console.log)
iota.api.getNewAddress(seed,{index:0,total:1,security:2},console.log)`

`var seed = "AAA999999999999999999999999999999999999999999999999999999999999999999999999999999";
iota.api.getNewAddress(seed,{index:0,total:0,security:2},console.log)
iota.api.getNewAddress(seed,{index:0,total:1,security:2},console.log)`

`var seed = "AAZ999999999999999999999999999999999999999999999999999999999999999999999999999999";
iota.api.getNewAddress(seed,{index:0,total:0,security:2},console.log)
iota.api.getNewAddress(seed,{index:0,total:1,security:2},console.log)`

**Comment by chrisdukakis** [comment]
Looks like `total==0` is ignored and address generation isn't deterministic.
With `total > 0` address generation works deterministically, whereas with no total or `total==0` `getNewAddress` calls `findTransactions` repeatedly to fetch an _unused_ address, hence the difference you observed. (seeds have been used on mainnet).

**Comment by mrbianchi** [comment]
then someone in docs is bad because the parameters that modify deterministic mechanism are:

> index: Int If the index is provided, the generation of the address is not deterministic.

> returnAll: Bool If true, it returns all addresses which were deterministically generated (until findTransactions returns null)

**Comment by chrisdukakis** [comment]
@mrbianchi I see what you mean, and agree that is confusing. I'll update the docs, but ideally all options except index (which is useful as offset) should be deprecated, and `getNewAddress` should simply return a new address using network provider or local store. Method for deterministic generation will be moved to crypto module. Seems quite straightforward & I prefer methods doing one thing and doing it well. What do you think?

**Comment by mrbianchi** [comment]
I dont like the idea of force to get new address interacting with a node

**Comment by chrisdukakis** [comment]
[Fixed](https://github.com/iotaledger/iota.lib.js/blob/9cb3b74e1df332a436e613e83d71573c6b4c685d/packages/core/test/integration/getNewAddress.test.ts#L70) as of `v1.0.0-alpha-1`. Passing `options.total=0` is now an error.

Regarding non-deterministic interaction with network, there will be a plan for moving to offline deterministic key index management. Right now there is a new pure method, [`generateAddresses`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.generateAddress) but _key index management should be implemented by the callers!_
