### ISSUE TITLE
.getNewAddress() not save created addresses

### ISSUE THREAD

**Issue by fsanano** [iotaledger/iota.lib.js#212]
I use test node: https://nodes.testnet.iota.org:443
When I create new address, in cb it returns. But when I try call .getAccountData() or .getTransfers() I just get empty array without addresses or transactions.
I tried .getAccountData() some time letter after creating new address, but still nothing.
Below are my methods:
```
import IOTA from 'iota.lib.js';
const iotaApi = new IOTA({
  provider: 'https://nodes.testnet.iota.org:443',
});

const iota = iotaApi.api;
iota.getNewAddress('MYSEED', {
  index: 0,
  total: 1,
  security: 3,
  checksum: true,
  returnAll: true,
}, async (error, address) => {
  if (error) {
    console.info('error', error);// eslint-disable-line
  } else {
    //return new address
    iota.getAccountData('MYSEED', (error, data) => {
      if (error) {
        console.info('error', error);// eslint-disable-line
      } else {
        console.log(data);
      }
    });
  }
});
```

```
async iotaFetchWalletBalance(address, seed) {
  iota.getAccountData(seed, (error, data) => {
    if (error) {
      console.error(error);
    } else {
      console.info('data', data);
      //return for example {latestAddress: "IKAZVTM9LOWXWTVDNYXJJMEHDVMODKX9FIPOKLWXHUWZTRTYEFAGGU9CVWNELBZWZYSVZRYAUQSAUZUMY", addresses: Array(0), transfers: Array(0), inputs: Array(0), balance: 0}
    }
  });
},

async iotaleFetchWalletTransactions(address, seed) {
  iota.getTransfers(seed, (error, txs) => {
    if (error) {
      console.error(error);
    } else {
      console.info('transactions', txs);
     //return empty array
    }
  });
},
```

**Comment by chrisdukakis** [comment]
@fsanano try to attach the address on the tangle for `getAccountData` and `getTransfers` to work. You can do that with a zero value transaction. Note that this stops working after snapshot.

**Comment by chrisdukakis** [comment]
@fsanano Use `sendTrytes` with an a zero value transfer:
```js
const transfer = [{
    address: 'your address here',
    value: 0,
    tag: '',
    message: ''
}]

iota.api.sendTransfer('', depth, minWightMagnitude,  transfers, (err, txs) => {
    if (err) {
        // ...
    }
    // ...
})
```

**Comment by chrisdukakis** [comment]
@fsanano `getTransfers` should work too, it utilizes the same functionality as `getAccountData`. 

Please join [IOTA Discord](https://discord.gg/7Gu2mG5), we can continue the discussion there! (#javascript channel)

**Comment by albertolive** [comment]
Hi, It's ```sendTransfer``` method depracted? I cannot find it in the library

**Comment by Thoralf-M** [comment]
@albertolive that was the old lib, now we have `sendTrytes()`
https://github.com/iotaledger/iota.js/blob/next/api_reference.md#coresendtrytestrytes-depth-minweightmagnitude-reference-callback

**Comment by albertolive** [comment]
Great, I'm using it now. But then, if I call ```getAccountData``` again, I don't see the new address that I created. 

What I do is:

1. ```getNewAddress``` method to get new address
2. ```prepareTransfers``` method and send the seed and transfers object with the new address created and with 0 value.
3. ```sendTrytes``` method and send the response of ```prepareTransfers```.
