### ISSUE TITLE
getNewAddress Returning Same address everytime

### ISSUE THREAD

**Issue by zeshanvirk** [iotaledger/iota.lib.js#224]
i'm using https://nodes.testnet.iota.org:443 iota node and i've a const seed, whenever i call getNewAddress method against that seed it returns me same address everytime, whereas according to docs it should return new address. 

seed is something like: HELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDHELLOWORLDH

**Comment by chrisdukakis** [comment]
Hi @zeshanvirk docs refer to address that haven't been used in transactions as _new_. Therefore `getNewAddress` will return the same address, as long as there are no associated transactions on the tangle. Sorry for confusion, I'll provide a better [description](https://github.com/iotaledger/iota.lib.js/pull/207/commits/00888a079c8e166e05242035a7bdbaabb0052f4c#diff-f395297f943b304cffe68e2229c2a04bR142) in #207

**Comment by zeshanvirk** [comment]
sure.

**Comment by chrisdukakis** [comment]
Documentation has beed [updated here](https://github.com/iotaledger/iota.lib.js/tree/next/packages/core#module_core.getNewAddress). Note that it applies for __`v >= 1.0.0-alpha.1`__
