### ISSUE TITLE
Cant install @iota/core as described in next branch ( typescript )

### ISSUE THREAD

**Issue by sascha1337** [iotaledger/iota.lib.js#237]
### Bug description
Docs of branch next (typescript version) describe to install @iota/core via NPM, but not on NPM registry

### Hardware Spec
OSX

### Steps To Reproduce
npm install  @iota/core

### Expected behaviour
Should install

### Actual behavior
404

### Errors

```
➜  paper git:(master) ✗ npm install @iota/core

npm ERR! code E404
npm ERR! 404 Not Found: @iota/core@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sascha/.npm/_logs/2018-06-25T05_33_48_401Z-debug.log
```

**Comment by anyong** [comment]
It hasn't been published to `npm` yet - that will go up today!

**Comment by anyong** [comment]
Done :)

**Comment by sascha1337** [comment]
Thanks !
