### ISSUE TITLE
Hard-coded total balance in multisig initiateTransfer

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.js#24]
In `Multisig.initiateTransfer`, the value of `totalBalance` is hardcoded to 1000.  It seems like this was intended to be for temporary/debugging purposes though:

```javascript
var totalBalance = 1000 // parseInt(balances.balances[0]);
```

 https://github.com/iotaledger/iota.lib.js/blob/master/lib/multisig/multisig.js#L248

**Comment by domschiener** [comment]
Thanks for the bug find. https://github.com/iotaledger/iota.lib.js/commit/f62a85b70de82e5160cc8105547d04e1153490d2
