### ISSUE TITLE
UTF-8 compatibility

### ISSUE THREAD

**Issue by za-uz** [iotaledger/iota.lib.js#243]
[This line](https://github.com/iotaledger/iota.lib.js/blob/develop/lib/utils/asciiToTrytes.js#L42) allows users to enter [Extended ASCII](https://en.wikipedia.org/wiki/Extended_ASCII) characters.

Extended ASCII is not compatible with UTF-8 which iota.lib.py uses. I know that iota.lib.js is the reference implementation and the other libraries should adapt to it (and not the other way around), but UTF-8 seems like a not so bad idea.

Changing the line to 
```
if (asciiValue > 127) {
```
would probably do the trick (for now) but I'm not at all familiar with iota.lib.js hence no pull request.

**Comment by chrisdukakis** [comment]
Hi @za-uz good point, this is now [fixed](https://github.com/iotaledger/iota.lib.js/blob/c810a98636fe421f6d032ef705564a61a451e099/packages/converter/src/ascii.ts#L48) as of **v1.0.0-alpha**.

**Comment by obany** [comment]
The other char code check in the v1.0.0-alpha code at https://github.com/iotaledger/iota.lib.js/blob/c810a98636fe421f6d032ef705564a61a451e099/packages/converter/src/ascii.ts#L57-L60 is now redundant with the regex check at the start of the toTrytes method.

**Comment by chrisdukakis** [comment]
Closing, redundant check removed in #256
