### ISSUE TITLE
Callback cannot be called error appears when calling getBalances()

### ISSUE THREAD

**Issue by CoogyEoin** [iotaledger/iota.lib.js#252]
### Bug description
When I go to call  the getBalances() function (which may be depreciated as I didn't see it under the list of functions on the main page) I am receiving an error stating the callback cannot be called. 
I believe I wasn't converting the address to trytes properly which is a mistake on my end but based on the code in the api file it should have returned an error stating invalid trytes. Instead I received the error below.

Code:
var account = iota.utils.toTrytes('blahblahblah');
var currentBalance = iota.api.getBalances(account, 100);

### Errors

        return callback(errors.invalidTrytes());
               ^

TypeError: callback is not a function
    at api.getBalances (C:\Users\Owner\node_modules\iota.lib.js\lib\api\api.js:183:16)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Blockchain Projects\Charging Station\Node.js\Iota.js:25:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by laumair** [comment]
@CoogyEoin `getBalances` and (almost) every API method requires a callback. 

`var currentBalance = iota.api.getBalances(account, 100);`  

- `getBalances` accepts an array of addresses as first parameter. 
- You are trying a direct assignment instead of passing the callback. 

Something like this should work:

```

iota.api.getBalances(['A'.repeat(81)], 100, function(err, balances){ })

```

**Comment by chrisdukakis** [comment]
@CoogyEoin you might also want to look at new [`@iota/core`](https://github.com/iotaledger/iota.lib.js/tree/next) package, which supports promises alongside callbacks.

I close this, `getBalances` [throws error](https://github.com/iotaledger/iota.lib.js/blob/49cec7296cb179a1c83b4b1fbb4c3fa129ca9f8f/lib/api/api.js#L193) for invalid addresses.
