### ISSUE TITLE
Show the optional field on document and function comment.

### ISSUE THREAD

**Issue by thieuanh1995hn** [iotaledger/iota.lib.js#261]
Hi guys i think you should show us that what field can define null (optional) on Java Client API which you have done well in Java script library : https://iotaledger.github.io/iota.lib.java/javadoc/jota/IotaAPI.html#sendTransfer-java.lang.String-int-int-int-java.util.List-java.util.List-java.lang.String-boolean-boolean-
For example.  In sendTransfer Api . We can define inputs parameter = null because it is optional and the code show that truth.

**Comment by chrisdukakis** [comment]
hey @thieuanh1995hn , I close this and opened a new one in java library repo.

**Comment by thieuanh1995hn** [comment]
Sorry . My mistake !
