### ISSUE TITLE
Using if condition instead of using while loop

### ISSUE THREAD

**Issue by peter279k** [iotaledger/iota.lib.js#271]
Consider this [line of code](https://github.com/iotaledger/iota.lib.js/blob/develop/lib/utils/utils.js#L248).

It looks like using the `while` loop make developers misunderstand behavior easily.
It easily misunderstand that this will cause the infinite loop.

How about using the `if` condition directly? I think it can be easy to understand theses behaviors.
This issue have many places in `transactionTrytes` method.

Thanks.

**Comment by th0br0** [comment]
I'm afraid you're misunderstanding what the code does.

```
var arr = [1,2,3];
while(arr.length < 5) {
  arr[arr.length] = 0;
}

arr == [1,2,3,0,0] == true // == true!
```

A mere `if` is not applicable, instead the code is equivalent to
```
let arr = [1,2,3];
arr = arr.concat(Array(5 - arr.length).fill(0));

arr == [1,2,3,0,0] == true // == true!
```

However, `Array.fill` was only added with ECMAScript 2015 (i.e. ES6!).
This package, `iota.lib.js` currently does not use `babel` or a similar transpiler. Hence, it's effectively limited to ES5.
I agree that a nice helper method could've been used here, but the `while` loop is just as expressive.

Closing as a wontfix.

**Comment by th0br0** [comment]
@peter279k Also, check out the rewrite targeting typescript which is pretty much there already! It's devoid of all these idiosynchrasies :) https://github.com/iotaledger/iota.lib.js/tree/next

**Comment by peter279k** [comment]
@th0br0, thank you for your help.
I have known this after your explanation.
