### ISSUE TITLE
Is function shouldYouReplay poorly named?

### ISSUE THREAD

**Issue by thisredone** [iotaledger/iota.lib.js#28]
As far as I can tell it doesn't mean that one should replay that transaction and more that one _can_ replay it, right?

**Comment by domschiener** [comment]
To be honest, I was debating that name for more than 30minutes when coming up with it. It's quite difficult to find a proper name that indicates what it's for. I'll probably just rename it to `canYouReattach`. Let me know if you have any better name suggestions
