### ISSUE TITLE
Move some dependencies to devDependencies to make npm install lighter

### ISSUE THREAD

**Issue by walling** [iotaledger/iota.lib.js#30]
Hi, I'm creating this issue because I think some of the package.json dependencies are not necessary for running this module (only for development). This will decrease the weight of the installed module when doing a `npm install --save iota.lib.js` in your local project.

The package.json have:

```
"dependencies": {
  "async": "^2.4.1",
  "big.js": "^3.1.3",
  "browserify": "^14.4.0",
  "mocha": "^3.4.2",
  "xmlhttprequest": "^1.8.0"
}
```

However it seems that only *async* and *xmlhttprequest* are actually used inside `lib/`. So maybe the other dependencies can be moved to devDependencies. Any reasons why it could not? Especially *browserify* is quite a big dependency with many sub-dependencies.

**Comment by anyong** [comment]
This is fixed in the next iteration of the library: https://github.com/iotaledger/iota.lib.js/blob/next/package.json
