### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by atypicalprogrammer** [iotaledger/iota.lib.js#37]
Issue on line 1480 of api.js;
                                   
```
var thisInclusion = tailTxStates[tailTxArray.indexOf(tailTx)];

Uncaught typeError: Cannot read property '0' of undefined
```

**Comment by janfiedler** [comment]
iota.lib.js v0.4.1
Issue on line api.js:1535

> 

Still get this error running on node.js, in random time. When looping function getAccountData().
Any idea?

>

**Comment by anyong** [comment]
I'm going to close this issue as it has been opened for quite some time with no additional information. If you are still seeing errors, please write a more descriptive explanation including steps to reproduce and re-open this issue.
