### ISSUE TITLE
Utils.fromTrytes accepts non-tryte values

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iota.lib.js#47]
`Utils.fromTrytes` doesn't validate input is Trytes (only that chars come in pairs):
```
>iota.utils.fromTrytes('AC1233')
"R￤￤"
```
these `￤` are due to: 
`TRYTE_VALUES.indexOf(trytes[0]);` `indexOf()` returns `-1` 
so `character = String.fromCharCode(-1+-1*27) => ￤ `

in the spirit of @nicoschtein validation additions,
I propose to return `null` if non-tryte char was found (can be done while looping).

in addition, [tests](https://github.com/iotaledger/iota.lib.js/blob/e500c06aa18106896040c61930ab9b13a89603e2/test/utils/utils.fromTrytes.js) for this unit first convert using `toTrytes()` - so edge cases like this aren't caught.

Credit to Laurence Tennant & his [tool](https://laurencetennant.com/iota-tools/) for making this interface accessable.

**Comment by vbakke** [comment]
I second this. 

It is an easy fix to insert a check on -1 in `fromTrytes()`.

```
        var firstValue = TRYTE_VALUES.indexOf(trytes[0]);
        var secondValue = TRYTE_VALUES.indexOf(trytes[1]);

        if (firstValue < 0 || secondValue < 0)   // <-- insert this
            return null;                         // <-- and this
            
        var decimalValue = firstValue + secondValue * 27;
```

**Comment by anyong** [comment]
The original issue described by @alon-e has been resolved in v1, unit tests here: https://github.com/iotaledger/iota.lib.js/blob/next/test/utils/fromTrytes.test.ts#L9
