### ISSUE TITLE
valid.isAddress return true regardless if checksum is correct or not, as long as the length is OK

### ISSUE THREAD

**Issue by frohal** [iotaledger/iota.lib.js#49]
Any 'valid' address of 81 trytes, si of course OK, and if I add 9 trytes more (as checksum) it's still valid, regardless of the added 9 trytes.
Should not this function verify checksum if provided ?  It does not, it only verifies that it is 9 trytes long...

both 'real' address : RQRKXKSMC9YEGOZOCVNPDPLNSFMMDIJKYDQWUE9YEUCHFDYZKZLLXFFIPTHOMPDYQTUIRNKUIAZSUBTFAHCKLPOMEY
and wrong address: RQRKXKSMC9YEGOZOCVNPDPLNSFMMDIJKYDQWUE9YEUCHFDYZKZLLXFFIPTHOMPDYQTUIRNKUIAZSUBTF9999999999
is considered 'valid' by the api-function.

**Comment by chrisdukakis** [comment]
`utils.isValidChecksum()` does checksum validation. 
`valid.isAddress()` checks length and if all chars are trytes.

**Comment by frohal** [comment]
Yes, and this is nothing but wrong.
The api-group is 'valid'.
and when you giv an address with checksum, it should validate the whole address. It should perhaps call the util-method, but it should not return 'true' for an address you cannot send to...

**Comment by domschiener** [comment]
You can send to an 81 trytes address regardless. Only on higher level applications (such as the GUI Wallet) we only allow for checksummed addressed to send funds to. This has nothing to do with the library.

**Comment by chrisdukakis** [comment]
Well, when you want to validate checksum you call `isValidChecksum()`.
It's not wrong, could be adjusted to avoid confusion maybe.

**Comment by frohal** [comment]
Yes, you can send to any 81-tryes, I know. But when the API is called 'valid.isAddress()' and takes 90 Trytes, it really should validate the last 9 as checksum.
The api fails if I send 89 Trytes, so it's very aware that it should be either 81 or 90, and then also very aware that the last 9 is checksum if you send 90...

And what higher-level applications has to do (like the GUI-wallet does), does not really concern this lib.
I was thinking of using it just to verify that an address entered on a web-page was valid, and was pretty sure that 'valid.isAddress()' was the correct methhod to use in the lib... But it turns out it was not... 
Why not just implement this as an actual address-check, with checksum ? There is other methods to verify that a string contains only trytes...  This, by it's naming, should really check address for validity...

**Comment by bmavity** [comment]
For what it's worth, I agree with @frohal. With an invalid checksum the method call produces an incorrect result.

I also understand that this issue is closed, I just wanted to provide some moral support to frohal. ;)
