### ISSUE TITLE
getInputs blocks whole process

### ISSUE THREAD

**Issue by robertkowalski** [iotaledger/iota.lib.js#55]
When I try to get the balances for a seed `getInputs` iterates over the start and end key to generate addresses: 

```js
        for (var i = start; i < end; i++) {

            var address = self._newAddress(seed, i, security, false);
            allAddresses.push(address);
        }
```
from: 
https://github.com/iotaledger/iota.lib.js/blob/221e7692e9bcb7db4427551c303a7f9fcf39e631/lib/api/api.js#L878

This leads to a blocking of the whole Node process until all addresses are generated.

Is there a way to run those async?

**Comment by anyong** [comment]
This uses a promise in the `next` branch: https://github.com/iotaledger/iota.lib.js/blob/next/lib/api/extended/createGetInputs.ts#L45

**Comment by robertkowalski** [comment]
<3 thank you!
