### ISSUE TITLE
Error: Invalid Response: Unsupported Media Type - when using the sandbox api

### ISSUE THREAD

**Issue by glumb** [iotaledger/iota.lib.js#57]
**Reproduce**

The following code
```js
var iota = new IOTA({
  'provider': 'https://sandbox.iota.org/api/v1/',
  'sandbox': true,
});
iota.api.getNodeInfo(function(error, success) {
    if (error) {
        console.error(error);
    } else {
        console.log(success);
    }
})
```
results in this error:

```
Error: Invalid Response: Unsupported Media Type
```

**Possible Solution**

Why was this line commented out:
https://github.com/iotaledger/iota.lib.js/blob/37c5a1b10d8d6d7c6d688443f7c5b474e64d7679/lib/utils/makeRequest.js#L33
Commenting it back in fixes this issue.

**Comment by numerized** [comment]
Same here any idea ?

**Comment by alon-e** [comment]
@domschiener 
 this is the commit that commented this out: https://github.com/iotaledger/iota.lib.js/commit/504f3f0d3360e75d825b37396c04d4040d4c9285#diff-eb60911997547306dac6b30bc58ba315

`temporarily disabled until IRI fix ` , on Feb 2. do you know what IRI fix was? is this comment-out still relevant? (the explanation was removed in https://github.com/iotaledger/iota.lib.js/commit/fc23c4c425281dcdbdb02cdd67b815fd93dfb2b1)

**Comment by trickstival** [comment]
I don't know what is that IRI fix, but I'm writing here cause I want to follow this issue to know what's going on

**Comment by chrisdukakis** [comment]
Closing this issue, as [sandbox](https://powbox.testnet.iota.org/) has been upgraded and works as expected with [`curl-remote`](https://www.npmjs.com/package/@iota/curl-remote) package.
