### ISSUE TITLE
[Bug] Issues with index of iota.api.getNewAddress()

### ISSUE THREAD

**Issue by kgrsajid** [iotaledger/iota.lib.js#73]
There is a possible bug in the iota.api.getNewAddress() method.

By not providing "index" field in the options parameter works correctly (returns the next unused address).
But providing a integer in the "index" field doesn't always return the correct address located in that index.

To recreate the problem, try to use pass a index value for which the associated address has already been used or attached to the tangle. Index of unused address seems to be working.

**Comment by th0br0** [comment]
We can't repro. Could you please provide a test case?

**Comment by chrisdukakis** [comment]
Make sure you pass `total` in `options`. If `total` is not passed to `getNewAddress` it will call `findTransactions()` and increment the index until a new unused address is found.

**Comment by kgrsajid** [comment]
@chrisdukakis Are you sure about that? If I pass `total` along with `index` in `options`, it returns multiple addresses (ignores `index`). Please try it yourself.

@th0br0 Check the following codes. **I have 13 used addresses**. This code always returns the next unused address even if I set `index` as less than 13. For the index value >= `13` looks fine.

`var iota = new IOTA({
		    'host': 'http://service.iotasupport.com',
		    'port': 14265
		});
		
		var seed = 'YOUR SEED';
		var options = { 
			checksum: true,
			security: 2,
			index: 3
		}
		iota.api.getNewAddress( seed, options, function( error, result ) {
		    console.log(result);
		    // Address:
		});`

**Comment by kgrsajid** [comment]
@th0br0 You didn't yet repro the issue?!

**Comment by th0br0** [comment]
I can't close, but:

```
 // Case 1: total
    //
    // If total number of addresses to generate is supplied, simply generate
    // and return the list of all addresses
```

```
 //  Case 2: no total provided
    //
    //  Continue calling findTransactions to see if address was already created
    //  if null, return list of addresses
```

Please read the documentation.
getNewAddress will return the next unused address. This is no bug.

**Comment by kgrsajid** [comment]
@th0br0 OMG! Who wrote this library?!

I was talking about `index`, not `total`! Please read my posts carefully. I've already provided a case.

If you don't know, getNewAddress also returns specific address based on `index`, not just next unused address!

**Comment by th0br0** [comment]
You have not provided a test or repro case. You have provided a code snippet copied from the documentation. That is something quite different.

`getNewAddress` will only return either:
* a set number of addresses from index to index+total
* all addresses that are checked for past transactions starting at index
* the first address after or at index without past transactions

If the address at `index` has been used, you will only see it returned if you either specify `total` or provide `returnAll`.

**Comment by kgrsajid** [comment]
Wow! I've lost my words!

It's really the most sophisticated function out there. Probably, we'll be able to transfer IOTA using this function in the future. (Because a function should do more than what it says in the documentation of course.)

I am closing this thread anyway. It seems like IOTA libraries are too perfect to have any bug in them.
