### ISSUE TITLE
[Task]: Change inputs property type of ITransactionEssence

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota.lib.js#889]
## Description

I might have misunderstood something, but I think the `inputs` property of `ITransactionEssence` could be typed better.

Current typing:

```
export interface ITransactionEssence extends ITypeBase<1> {
    /.../
    /**
     * The inputs of the transaction.
     */
    inputs: IUTXOInput[];
    /.../
}
```

Expected:

```
export interface ITransactionEssence extends ITypeBase<1> {
    /.../
    inputs: InputTypes[];
    /**
     * The commitment to the referenced inputs.
     */
    /.../
}
```

## Motivation

Consistency

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by brancoder** [comment]
Hi Tuditi, thx for your feedback.
The typing is correct because transaction essence describes the essence data making up a transaction by defining its inputs, outputs and an optional payload. You can find more details on this [link](https://wiki.iota.org/goshimmer/protocol_specification/components/ledgerstate)

The following table structure describes the entirety of a _Transaction Payload_ in its serialized form:
* <details>
    <summary>Subschema Notation</summary>
    <table>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
        <tr>
            <td><code>oneOf</code></td>
            <td>One of the listed subschemas.</td>
        </tr>
        <tr>
            <td><code>optOneOf</code></td>
            <td>Optionally one of the listed subschemas.</td>
        </tr>
        <tr>
            <td><code>anyOf</code></td>
            <td>Any (one or more) of the listed subschemas.</td>
        </tr>
    </table>
</details>

<p></p>
  
<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>Payload Type</td>
    <td>uint32</td>
    <td>
      Set to <strong>value 0</strong> to denote a <i>Transaction Payload</i>.
    </td>
  </tr>
  <tr>
    <td valign="top">Essence <code>oneOf</code></td>
    <td colspan="2">
      <details open="true">
        <summary>Transaction Essence</summary>
        <blockquote>
          Describes the essence data making up a transaction by defining its inputs, outputs and an optional payload.
        </blockquote>
        <table>
          <tr>
            <td><b>Name</b></td>
            <td><b>Type</b></td>
            <td><b>Description</b></td>
          </tr>
          <tr>
            <td>Transaction Type</td>
            <td>uint8</td>
            <td>
              Set to <strong>value 0</strong> to denote a <i>Transaction Essence</i>.
            </td>
          </tr>
          <tr>
            <td>Inputs Count</td>
            <td>uint16</td>
            <td>The number of input entries.</td>
          </tr>
          <tr>
            <td valign="top">Inputs <code>anyOf</code></td>
            <td colspan="2">
              <details>
                <summary>UTXO Input</summary>
                <blockquote>
                  Describes an input which references an unspent transaction output to consume.
                </blockquote>
                <table>
                  <tr>
                    <td><b>Name</b></td>
                    <td><b>Type</b></td>
                    <td><b>Description</b></td>
                  </tr>
                  <tr>
                    <td>Input Type</td>
                    <td>uint8</td>
                    <td>
                      Set to <strong>value 0</strong> to denote an <i>UTXO Input</i>.
                    </td>
                  </tr>
                  <tr>
                    <td>Transaction ID</td>
                    <td>ByteArray[32]</td>
                    <td>The BLAKE2b-256 hash of the transaction payload containing the referenced output.</td>
                  </tr>
                  <tr>
                    <td>Transaction Output Index</td>
                    <td>uint16</td>
                    <td>The output index of the referenced output.</td>
                  </tr>
                </table>
              </details>
            </td>
          </tr>
          <tr>
            <td>Outputs Count</td>
            <td>uint16</td>
            <td>The number of output entries.</td>
          </tr>
          <tr>
            <td valign="top">Outputs <code>anyOf</code></td>
            <td colspan="2">
              <details>
                <summary>SigLockedSingleOutput</summary>
                <blockquote>
                  Describes a deposit to a single address which is unlocked via a signature.
                </blockquote>
                <table>
                  <tr>
                    <td><b>Name</b></td>
                    <td><b>Type</b></td>
                    <td><b>Description</b></td>
                  </tr>
                  <tr>
                    <td>Output Type</td>
                    <td>uint8</td>
                    <td>
                      Set to <strong>value 0</strong> to denote a <i>SigLockedSingleOutput</i>.
                    </td>
                  </tr>
                  <tr>
                    <td valign="top">Address <code>oneOf</code></td>
                    <td colspan="2">
                      <details>
                        <summary>Ed25519 Address</summary>
                        <table>
                          <tr>
                            <td><b>Name</b></td>
                            <td><b>Type</b></td>
                            <td><b>Description</b></td>
                          </tr>
                          <tr>
                            <td>Address Type</td>
                            <td>uint8</td>
                            <td>
                              Set to <strong>value 0</strong> to denote an <i>Ed25519 Address</i>.
                            </td>
                          </tr>
                          <tr>
                            <td>Address</td>
                            <td>ByteArray[32]</td>
                            <td>The raw bytes of the Ed25519 address which is the BLAKE2b-256 hash of the public key.</td>
                          </tr>
                        </table>
                      </details>
                    </td>
                  </tr>
                  <tr>
                    <td>Amount</td>
                    <td>uint64</td>
                    <td>The amount of tokens to deposit.</td>
                  </tr>
                </table>
              </details>
              <details>
                <summary>SigLockedDustAllowanceOutput</summary>
                <blockquote>
                  Describes a deposit which as a special property also alters the dust allowance of the target address.
                </blockquote>
                <table>
                  <tr>
                    <td><b>Name</b></td>
                    <td><b>Type</b></td>
                    <td><b>Description</b></td>
                  </tr>
                  <tr>
                    <td>Output Type</td>
                    <td>uint8</td>
                    <td>
                      Set to <strong>value 1</strong> to denote a <i>SigLockedDustAllowanceOutput</i>.
                    </td>
                  </tr>
                  <tr>
                    <td valign="top">Address <code>oneOf</code></td>
                    <td colspan="2">
                      <details>
                        <summary>Ed25519 Address</summary>
                        <table>
                          <tr>
                            <td><b>Name</b></td>
                            <td><b>Type</b></td>
                            <td><b>Description</b></td>
                          </tr>
                          <tr>
                            <td>Address Type</td>
                            <td>uint8</td>
                            <td>
                              Set to <strong>value 0</strong> to denote an <i>Ed25519 Address</i>.
                            </td>
                          </tr>
                          <tr>
                            <td>Address</td>
                            <td>ByteArray[32]</td>
                            <td>The raw bytes of the Ed25519 address which is the BLAKE2b-256 hash of the public key.</td>
                          </tr>
                        </table>
                      </details>
                    </td>
                  </tr>
                  <tr>
                    <td>Amount</td>
                    <td>uint64</td>
                    <td>The amount of tokens to deposit.</td>
                  </tr>
                </table>
              </details>
            </td>
          </tr>
          <tr>
            <td>Payload Length</td>
            <td>uint32</td>
            <td>The length in bytes of the optional payload.</td>
          </tr>
          <tr>
            <td valign="top">Payload <code>optOneOf</code></td>
            <td colspan="2">
              <details>
                <summary>Generic Payload</summary>
                <blockquote>
                  An outline of a generic payload.
                </blockquote>
                <table>
                  <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                  </tr>
                  <tr>
                    <td>Payload Type</td>
                    <td>uint32</td>
                    <td>
                      The type of the payload. It will instruct the node how to parse the fields that follow.
                    </td>
                  </tr>
                  <tr>
                    <td>Data Fields</td>
                    <td>ANY</td>
                    <td>A sequence of fields, where the structure depends on <code>Payload Type</code>.</td>
                  </tr>
                </table>
              </details>
          <tr>
        </table>
      </details>
    </td>
  </tr>
  <tr>
    <td>Unlock Blocks Count</td>
    <td>uint16</td>
     <td>The number of unlock block entries. It must match the field <code>Inputs Count</code>.</td>
  </tr>
  <tr>
    <td valign="top">Unlock Blocks <code>anyOf</code></td>
    <td colspan="2">
      <details open="true">
        <summary>Signature Unlock Block</summary>
        <blockquote>
          Defines an unlock block containing a signature.
        </blockquote>
        <table>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
          </tr>
          <tr>
            <td>Unlock Type</td>
            <td>uint8</td>
            <td>
              Set to <strong>value 0</strong> to denote a <i>Signature Unlock Block</i>.
            </td>
          </tr>
          <tr>
            <td valign="top">Signature <code>oneOf</code></td>
            <td colspan="2">
              <details>
                <summary>Ed25519 Signature</summary>
                <table>
                  <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Description</th>
                  </tr>
                  <tr>
                    <td>Signature Type</td>
                    <td>uint8</td>
                    <td>
                      Set to <strong>value 0</strong> to denote an <i>Ed25519 Signature</i>.
                    </td>
                  </tr>
                  <tr>
                    <td>Public key</td>
                    <td>ByteArray[32]</td>
                    <td>The Ed25519 public key of the signature.</td>
                  </tr>
                  <tr>
                    <td>Signature</td>
                    <td>ByteArray[64]</td>
                    <td>The Ed25519 signature signing the Blake2b-256 hash of the serialized <i>Transaction Essence</i>.</td>
                  </tr>
                </table>
              </details>
            </td>
          </tr>
        </table>
      </details>
      <details open="true">
        <summary>Reference Unlock Block</summary>
        <blockquote>
          References a previous unlock block, where the same unlock block can be used for multiple inputs.
        </blockquote>
        <table>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
          </tr>
          <tr>
            <td>Unlock Type</td>
            <td>uint8</td>
            <td>
              Set to <strong>value 1</strong> to denote a <i>Reference Unlock Block</i>.
            </td>
          </tr>
          <tr>
            <td>Reference</td>
            <td>uint16</td>
            <td>Represents the index of a previous unlock block.</td>
          </tr>
        </table>
      </details>
    </td>
  </tr>
</table>
