### ISSUE TITLE
Wrong argument in calling ascii.toTrytes()

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iota.lib.js#9]
The argument in calling ascii.toTrytes(trytes)  should be the variable string, not the variable trytes.

/**
*   Convert bytes to trytes
*
*   @method toTrytes
*   @param {string} string
*   @param {string} type
*   @returns {string} address (without checksum)
**/
var toTrytes = function(string, type) {

    if (type === "ascii") {
        return ascii.toTrytes(trytes);
    }
}

**Comment by domschiener** [comment]
To be honest, I haven't looked at the toTrytes function in quite some time. I will try and get to it this weekend hopefully.
