### ISSUE TITLE
Error: Invalid attached Trytes provided

### ISSUE THREAD

**Issue by surjikal** [iotaledger/iota.lib.js#92]
Getting the following error when calling `sendTransfer`:

```
VM1804:3501 Uncaught (in promise) Error: Invalid attached Trytes provided
    at Object.invalidAttachedTrytes (eval at module.exports (addScript.js:8), <anonymous>:3501:16)
    at api.storeTransactions (eval at module.exports (addScript.js:8), <anonymous>:352:32)
    at api.storeAndBroadcast (eval at module.exports (addScript.js:8), <anonymous>:464:10)
    at eval (eval at module.exports (addScript.js:8), <anonymous>:540:22)
    at doNext (curl.lib.js:67)
    at curl.lib.js:78
    at <anonymous>
```

To reproduce, run the following:
```javascript
let CURL = require('curl.lib.js')
let IOTA = require('iota.lib.js')
let seed = "UFLKWXVHYTPDBAOJS9CQMGNRZEI" // This was randomly generated
let iota = new IOTA({host:"http://iota.bitfinex.com", port:80})
CURL.overrideAttachToTangle(iota.api);
CURL.init()
iota.api.getNewAddress(seed, {}, (error, address) => {
    console.log("ADDRESS:", address)
    if (error) throw error;
    let transfers = [{
        'address': address,
        'message': iota.utils.toTrytes("testing"),
        'value': 0,
        'tag': 'SURJIKAL'
    }]
    iota.api.sendTransfer(seed, 4, 14, transfers, (error, results) => {
        if (error) throw error;
        console.log("RESULTS:", results)
    });
});
```

This was working fine before the latest update. I traced the error to `iota.lib.js/isArrayOfAttachedTrytes`. The tryte that gets passed in this function is `2727` characters long, but the function expected it to be `2673` characters long. I don't know what this means but that's what causes the validation to fail.

Similar error is thrown if I remove the `CURL` stuff.

**Comment by surjikal** [comment]
Digging around the source, seems like `Utils.transactionTrytes` is returning a tryte of length `2727`.

**Comment by surjikal** [comment]
Removing the `transaction.obsoleteTag` and `transaction.tag` from the result of `Utils.transactionTrytes` seems to make it return a tryte of the correct length.

**Comment by surjikal** [comment]
Hm I think it might be because my library was not up to date. I pulled it using bower.

**Comment by surjikal** [comment]
Yeah nevermind, this problem is related to outdated `iota.lib.js` and `curl.lib.js`. Just make sure they are updated and it all works.

**Comment by Aldian1** [comment]
@surjikal Im trying to do my own implementation but it is not working correctly. Getting the same error message that you got but both my libs are up to date. Did you change anything in your implementation above to get it to work in the end? Ive tried running your code alongside mine and both out put the same error message.

**Comment by surjikal** [comment]
@Aldian1 It's been a while, I think what I ended up doing is extracting the code from the wallet repo.

**Comment by thisredone** [comment]
I'm having the same problem
