### ISSUE TITLE
Implement syntactic checks

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota.lib.js#929]
## Description

Implement syntactic checks for blocks and payloads based on the TIPs. Such checks should be carried out before/after serializing/deserializing objects.

AFAIK iota.go implements it in a way that you can tell the serialization/deserialization function whether to perform syntactic checks during the operation.

Edit:
- Implement the "entrypoint" logic in singleNodeClient#blockSubmit method
- Make the validation optional 

Needs:
https://github.com/iotaledger/iota.js/issues/1003
https://github.com/iotaledger/iota.js/issues/1004
https://github.com/iotaledger/iota.js/issues/1005
https://github.com/iotaledger/iota.js/issues/1006
https://github.com/iotaledger/iota.js/issues/1036
https://github.com/iotaledger/iota.js/issues/1038

## Motivation

Catches syntactic errors on client side.

**Comment by msarcev** [comment]
This needs to be split to smaller tasks.

**Comment by msarcev** [comment]
Left to do:
- Expose all the needed validation functions
- Add the entrypoint logic for validation
- Review the code

**Comment by brancoder** [comment]
https://github.com/iotaledger/iota.js/issues/929#issuecomment-1321993986
- Expose all the needed validation functions
- Add the entrypoint logic for validation

Resolved in PR https://github.com/iotaledger/iota.js/pull/1055
