### ISSUE TITLE
how to caculate Transaction Id

### ISSUE THREAD

**Issue by coboywei** [iotaledger/iota.lib.js#933]
## Description

i need Transaction Id, need  SingleNodeClient.messageSubmit return txid, not message id

## Motivation

exchanges need txid

## Requirements

Write a list of what you want this feature to do.

1.  when we contruct a transaction, we use txid, keep the data api union
2.  keep same with BTC
3. 

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by msarcev** [comment]
Hello @coboywei, 
you can compute the `transactionId` from the transaction payload like this:

```
import { Blake2b } from "@iota/crypto.js";
import { Converter, WriteStream } from "@iota/util.js";
import { serializeTransactionPayload } from "@iota/iota.js";

const writeStream = new WriteStream();
serializeTransactionPayload(writeStream, payload);

const transactionId = Converter.bytesToHex(
    Blake2b.sum256(writeStream.finalBytes())
);
```
where `payload` is the transaction payload from your message.
