### ISSUE TITLE
Helper function to return blockID from a given block object

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/iota.lib.js#951]
## Description

A function that returns the blockID (Blake2b-256 hash) of a given block object, similar to the existing helper function, which returns the [blockID for a given milestone payload](https://github.com/iotaledger/iota.js/blob/feat/stardust/packages/iota/docs/api.md#blockidfrommilestonepayload).

## Motivation

Often needed functionality, which shouldn't have to be manually implemented by every user.

## Requirements

> ### blockIdFromBlock
> 
> ▸ **blockIdFromBlock**(`protocolVersion`, `block`): `string`
> 
> Compute a blockId from a block object.
> 
> #### Parameters
> 
> | Name | Type | Description |
> | :------ | :------ | :------ |
> | `protocolVersion` | `number` | The protocol version to use. |
> | `block` | `object` | The block object. |
> 
> #### Returns
> 
> `string`
> 
> The blockId of the block.

Input > Block
```json
{
	"protocolVersion": 2,
	"parents": [
		"0x0abece72c2d340329186c4f54c7a1fa1a54054947d41391102166651352218e8",
		"0x373af857205a4ba360897275d6fefccd657b4320543045d17c3b8507ba020aac",
		"0x6ed3ae33d09cceb71f70d30cf1ef7e73a8c4b26ba8d0fa661ee76506a80430d7",
		"0x8dd6cc51f2532af096115223dde368d45344b4bee81228d8f4a2f2985f8155bb"
	],
	"payload": {
		"type": 5,
		"tag": "0x484f524e4554205370616d6d6572",
		"data": "0x57652061726520616c6c206d616465206f662073746172647573742e0a436f756e743a203334313130320a54696d657374616d703a20323032322d30382d30325430373a35373a32355a0a54697073656c656374696f6e3a20343830c2b573"
	},
	"nonce": "736"
}
```

Output > BlockID
```
0x0fbe2bca606b717d635f379c87fed226568befb0548085bee184c4c5bba27fd0
```

## Open questions (optional)

No

## Are you planning to do it yourself in a pull request?

No

**Comment by msarcev** [comment]
We already have a function like this, here: 
https://github.com/iotaledger/iota.js/blob/6bb8933f3ed065153df2a5b6cc855badd2d7b996/packages/iota/src/utils/transactionHelper.ts#L44
