### ISSUE TITLE
Null from iota.utils.fromTrytes

### ISSUE THREAD

**Issue by Palabola** [iotaledger/iota.lib.js#96]
Here is a simple example which I encountered during create a new transfer:

```
var message =  iota.utils.toTrytes("hello world");  // WCTC9D9DCDEAKDCDFD9DSC
// Work fine with console.log(iota.utils.fromTrytes(message )); --> hello world

```
Then I created the transaction:

```
attached.signatureMessageFragment = 'WCTC9D9DCDEAKDCDFD9DSC99999.....';
// console.log(iota.utils.fromTrytes(attached.signatureMessageFragment)); --> null 
```

Why it is null? If is there a rule how many "9999" should be cleaned up from the response why it isn't documented?

**Comment by th0br0** [comment]
Number of trytes passed to `fromTrytes` must be even.

**Comment by envoy-mcapodici** [comment]
@th0br0 the value returned from findTransactionObjects or getBundle in signatureMessageFragment is of odd length i.e. 2187 

Which of the following do you recommend:

1. Caller of toTrytes has to normalize by chopping off last trite
2. toTrytes is updated to do above in case that input is odd

I'd prefer 2 and happy to submit PR

**Comment by mcapodici** [comment]
@th0br0 the value returned from findTransactionObjects or getBundle in signatureMessageFragment is of odd length i.e. 2187

Which of the following do you recommend:

    Caller of toTrytes has to normalize by chopping off last trite
    toTrytes is updated to do above in case that input is odd

I'd prefer 2 and happy to submit PR

**Comment by anyong** [comment]
@mcapodici I'm not sure we want to make that assumption in the library, and the caller should probably be the one doing the normalization. @chrisdukakis do you agree? If so, we can close this issue.

**Comment by chrisdukakis** [comment]
`fromTrytes()` was renamed to `trytesToAscii()` in **v1.0.0-alpha** and [throws error for trytes of odd length](https://github.com/iotaledger/iota.lib.js/blob/c810a98636fe421f6d032ef705564a61a451e099/packages/converter/test/trytesToAscii.test.ts#L24). I'm closing this issue, with length check it shouldn't be frustrating. Also documented [here](https://github.com/iotaledger/iota.lib.js/tree/next/packages/converter#module_converter.trytesToAscii).
