### ISSUE TITLE
Add "Get Balance" How To

### ISSUE THREAD

**Issue by huhn511** [iotaledger/iota.lib.js#998]
## Description

Add "Get Balance" How To for the wiki

- Show how to use the `getBalance` function
- Get Balance for a specific address
- How to show balance of native tokens and nfts?

**Comment by msarcev** [comment]
* There are some examples showing usage of `getBalance` in `packages/iota/examples/transaction/src/index.ts` and `packages/iota/examples/browser/index.html`. 
Does that help ?
* Check the `highlevel/addressBalance.ts` file.
* For NFT/Native tokens, you need to fetch the unspent output types for an address through indexer endpoints (check `src/clients/plugins/indexerPluginClient.ts`, the `nfts` function for NFTs), this will get you the outputIds, then you can use `src/clients/singleNodeClient.ts` for fetch output details for each outputId, and there's the data about NFTs for example. Native tokens can be in any output (basic/nft/alias).
